"""Uzpolitex custom fieldlari — standart doctype'larga qo'shimchalar.

Idempotent: har `bench migrate` da after_migrate hook orqali qayta tekshiriladi
(create_custom_fields mavjud fieldlarni yangilaydi, dublikat yaratmaydi).
"""

from frappe.custom.doctype.custom_field.custom_field import create_custom_fields

MANUFACTURE = "eval:doc.purpose=='Manufacture'"

SMENA_OPTIONS = "\n1-Смена\n2-Смена\n3-Смена"


def get_custom_fields():
	return {
		"Stock Entry": [
			dict(
				fieldname="uz_smena_sec",
				fieldtype="Section Break",
				label="Производственная смена",
				insert_after="stock_entry_type",
				depends_on=MANUFACTURE,
			),
			dict(
				fieldname="uz_smena",
				fieldtype="Select",
				label="Смена",
				options=SMENA_OPTIONS,
				insert_after="uz_smena_sec",
				mandatory_depends_on=MANUFACTURE,
			),
			dict(
				fieldname="uz_stanok",
				fieldtype="Link",
				options="Workstation",
				label="Станок",
				insert_after="uz_smena",
				# Ткацкий jurnalidan yaratilgan hujjatda stanoklar jurnal ichida —
				# bitta stanok talab qilinmaydi
				mandatory_depends_on="eval:doc.purpose=='Manufacture' && !doc.uz_jurnal && !doc.uz_lam_jurnal && !doc.uz_pechat_jurnal && !doc.uz_konvert_jurnal",
			),
			dict(fieldname="uz_smena_col", fieldtype="Column Break", insert_after="uz_stanok"),
			dict(
				fieldname="uz_xodim",
				fieldtype="Link",
				options="Employee",
				label="Сотрудник",
				insert_after="uz_smena_col",
				mandatory_depends_on=MANUFACTURE,
			),
			dict(
				fieldname="uz_xodim_nomi",
				fieldtype="Data",
				label="Ф.И.О.",
				fetch_from="uz_xodim.employee_name",
				read_only=1,
				insert_after="uz_xodim",
			),
			dict(
				fieldname="uz_pokazatel_sec",
				fieldtype="Section Break",
				label="Показатели смены",
				insert_after="get_stock_and_rate",
				depends_on=MANUFACTURE,
			),
			dict(
				fieldname="uz_sht",
				fieldtype="Int",
				label="ШТ (кол-во намоток)",
				non_negative=1,
				insert_after="uz_pokazatel_sec",
				description="Вводится вручную из журнала смены",
			),
			dict(
				fieldname="uz_namotka",
				fieldtype="Float",
				label="Намотка (КГ)",
				precision="2",
				non_negative=1,
				insert_after="uz_sht",
				description="Qo'lda kiritiladi (Exceldagi Намотка ustuni kabi)",
			),
			dict(fieldname="uz_kpi_col", fieldtype="Column Break", insert_after="uz_namotka"),
			dict(
				fieldname="uz_v_1_sht",
				fieldtype="Float",
				label="В 1 ШТ (КГ)",
				precision="3",
				read_only=1,
				insert_after="uz_kpi_col",
			),
			dict(
				fieldname="uz_raznitsa",
				fieldtype="Float",
				label="Разница (КГ)",
				precision="2",
				read_only=1,
				insert_after="uz_v_1_sht",
				description="Выход (ГП + отход) минус расход сырья; справочно",
			),
			dict(
				fieldname="uz_jurnal",
				fieldtype="Link",
				options="Tkatskiy Jurnal",
				label="Журнал Ткацкий",
				read_only=1,
				insert_after="uz_smena_sec",
				depends_on="eval:doc.uz_jurnal",
				description="Документ создан автоматически из журнала смены",
			),
			dict(
				fieldname="uz_lam_jurnal",
				fieldtype="Link",
				options="Laminat Jurnal",
				label="Журнал Ламинат",
				read_only=1,
				insert_after="uz_jurnal",
				depends_on="eval:doc.uz_lam_jurnal",
				description="Документ создан автоматически из журнала смены",
			),
			dict(
				fieldname="uz_rezka_jurnal",
				fieldtype="Link",
				options="Rezka Jurnal",
				label="Журнал Резка",
				read_only=1,
				insert_after="uz_lam_jurnal",
				depends_on="eval:doc.uz_rezka_jurnal",
				description="Документ создан автоматически из журнала резки",
			),
			dict(
				fieldname="uz_pechat_jurnal",
				fieldtype="Link",
				options="Pechat Jurnal",
				label="Журнал Печать",
				read_only=1,
				insert_after="uz_rezka_jurnal",
				depends_on="eval:doc.uz_pechat_jurnal",
				description="Документ создан автоматически из журнала печати",
			),
			dict(
				fieldname="uz_konvert_jurnal",
				fieldtype="Link",
				options="Konvert Jurnal",
				label="Журнал Конверт",
				read_only=1,
				insert_after="uz_pechat_jurnal",
				depends_on="eval:doc.uz_konvert_jurnal",
				description="Документ создан автоматически из журнала конверта",
			),
			dict(
				fieldname="uz_kk_jurnal",
				fieldtype="Link",
				options="KK Jurnal",
				label="Журнал КК",
				read_only=1,
				insert_after="uz_konvert_jurnal",
				depends_on="eval:doc.uz_kk_jurnal",
				description="Документ создан автоматически из журнала КК",
			),
			dict(
				fieldname="uz_press_jurnal",
				fieldtype="Link",
				options="Press Jurnal",
				label="Журнал Пресс",
				read_only=1,
				insert_after="uz_kk_jurnal",
				depends_on="eval:doc.uz_press_jurnal",
				description="Документ создан автоматически из журнала пресса",
			),
		],
		"Item": [
			dict(
				fieldname="uz_norma_sec",
				fieldtype="Section Break",
				label="Норма (Uzpolitex)",
				insert_after="item_group",
				collapsible=1,
			),
			dict(
				fieldname="uz_norma_min",
				fieldtype="Float",
				label="Норма мин",
				precision="3",
				insert_after="uz_norma_sec",
				description="Экструдор: кг в 1 шт. Ткацкий: грамм на 1 метр",
			),
			dict(fieldname="uz_norma_col", fieldtype="Column Break", insert_after="uz_norma_min"),
			dict(
				fieldname="uz_norma_max",
				fieldtype="Float",
				label="Норма макс",
				precision="3",
				insert_after="uz_norma_col",
			),
			dict(
				fieldname="uz_metr_10000",
				fieldtype="Float",
				label="Метр на 10 000 шт",
				precision="1",
				insert_after="uz_norma_max",
				description="Конверт: расход печатного рулона (М) на 10 000 мешков",
			),
			# --- Босма қоп дизайни (Печать) ---
			dict(
				fieldname="uz_qop_sec",
				fieldtype="Section Break",
				label="Босма қоп дизайни (Печать)",
				insert_after="uz_metr_10000",
				collapsible=1,
			),
			dict(
				fieldname="uz_qop",
				fieldtype="Check",
				label="Босма қоп",
				insert_after="uz_qop_sec",
				description="Бу маҳсулот босма қоп (заказ) бўлса белгиланг — краска нормаси ҳисобланади.",
			),
			dict(
				fieldname="uz_dizayn_old",
				fieldtype="Link",
				options="Pechat Dizayn",
				label="Олд дизайн",
				insert_after="uz_qop",
				depends_on="uz_qop",
			),
			dict(
				fieldname="uz_dizayn_orqa",
				fieldtype="Link",
				options="Pechat Dizayn",
				label="Орқа дизайн",
				insert_after="uz_dizayn_old",
				depends_on="uz_qop",
				description="Бўш = оқ/универсал орқа (краска сарфланмайди).",
			),
			dict(
				fieldname="uz_dizayn_lenta",
				fieldtype="Link",
				options="Pechat Dizayn",
				label="Лента / ён дизайн",
				insert_after="uz_dizayn_orqa",
				depends_on="uz_qop",
			),
			dict(fieldname="uz_qop_col", fieldtype="Column Break", insert_after="uz_dizayn_lenta"),
			dict(
				fieldname="uz_en_cm",
				fieldtype="Float",
				label="Эни, см",
				precision="1",
				insert_after="uz_qop_col",
				depends_on="uz_qop",
			),
			dict(
				fieldname="uz_boy_cm",
				fieldtype="Float",
				label="Бўйи, см",
				precision="1",
				insert_after="uz_en_cm",
				depends_on="uz_qop",
			),
			dict(
				fieldname="uz_lenta_en_cm",
				fieldtype="Float",
				label="Лента эни, см",
				precision="1",
				default="11",
				insert_after="uz_boy_cm",
				depends_on="uz_qop",
				description="Ён гуссет кенглиги (одатда ~11 см). Лента дизайн бўлса ишлатилади.",
			),
			dict(
				fieldname="uz_bosma_rulon",
				fieldtype="Link",
				options="Item",
				label="Босма рулон",
				read_only=1,
				insert_after="uz_lenta_en_cm",
				depends_on="uz_qop",
				description="Шу заказ учун босилган рулон (Печать чиқими, Конверт расходи). Авто яратилади.",
			),
			# --- Краска: тури, ранги, аралашма ретсепти (Печать) ---
			dict(
				fieldname="uz_kraska_sec",
				fieldtype="Section Break",
				label="Краска (Uzpolitex)",
				insert_after="uz_bosma_rulon",
				collapsible=1,
				depends_on="eval:doc.item_group=='Сырьё - Печать'",
			),
			dict(
				fieldname="uz_kraska_turi",
				fieldtype="Select",
				label="Краска тури",
				options="Асосий\nАралашма",
				default="Асосий",
				insert_after="uz_kraska_sec",
				description="Асосий = сотиб олинадиган соф ранг. Аралашма = 1-2 асосийдан ясалади.",
			),
			dict(
				fieldname="uz_rgb",
				fieldtype="Data",
				label="Ранг (HEX)",
				insert_after="uz_kraska_turi",
				description="Масалан #08afad. AI аралашма ретсептини шу рангга қараб таклиф қилади.",
			),
			dict(
				fieldname="uz_retsept",
				fieldtype="Table",
				label="Аралашма ретсепти",
				options="Uzpolitex Kraska Retsept",
				insert_after="uz_rgb",
				depends_on="eval:doc.uz_kraska_turi=='Аралашма'",
			),
		],
		"Sales Order": [
			# --- Зaказ киритиш: қоп + расм + ўлчам (Item авто яратилади) ---
			dict(
				fieldname="uz_zakaz_sec",
				fieldtype="Section Break",
				label="Қоп заказлар (Печать)",
				insert_after="customer_name",
				description="Ҳар қатор = 1 қоп. Сақлаганда қоп Item ва дизайн авто яратилади, "
				"краска нормаси ҳисобланади.",
			),
			dict(
				fieldname="uz_qop_zakazlar",
				fieldtype="Table",
				label="Қоп заказлар",
				options="Uzpolitex Qop Zakaz",
				insert_after="uz_zakaz_sec",
			),
			dict(
				fieldname="uz_kraska_sec",
				fieldtype="Section Break",
				label="Краска нормаси (Печать)",
				insert_after="items",
				collapsible=1,
			),
			dict(
				fieldname="uz_kraska_gm2",
				fieldtype="Float",
				label="г/м² (тахминий)",
				precision="2",
				default="2",
				insert_after="uz_kraska_sec",
				description="1 м² тўла босмага кетадиган краска (г). Ҳозирча тахминий — кейин Печать сменаси факти билан ўз-ўзидан калибрланади.",
			),
			dict(
				fieldname="uz_kraska_html",
				fieldtype="HTML",
				insert_after="uz_kraska_gm2",
				options="<div class='text-muted small'>«Краска нормасини ҳисобла» тугмаси ҳар қатор қоп дизайни × ўлчам × сони асосида ҳар ранг бўйича кг ни ҳисоблайди.</div>",
			),
			dict(
				fieldname="uz_kraska_normasi",
				fieldtype="Table",
				label="Краска нормаси",
				options="Uzpolitex Kraska Norma",
				insert_after="uz_kraska_html",
				read_only=1,
			),
		],
		"Workstation": [
			dict(
				fieldname="uz_bolim",
				fieldtype="Link",
				options="Department",
				label="Отдел (цех)",
				insert_after="workstation_type",
			),
		],
	}


def apply():
	create_custom_fields(get_custom_fields(), ignore_validate=True)
